#!/bin/sh

# Set these paths appropriately

BIN="$PWD/treetagger/bin"
CMD="$PWD/treetagger/cmd"
LIB="$PWD/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian.par

grep -v '^$' $* |
perl -pe 's/^/<s> /;s/$/ <\/s>/;tr/ /\n/' |
grep -v '^$' |
$TAGGER $OPTIONS $PARFILE
