#!/bin/sh

# Set these paths appropriately

BIN="$PWD/treetagger/bin"
CMD="$PWD/treetagger/cmd"
LIB="$PWD/treetagger/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/english.par

perl -pe 'tr/ /\n/' $* |
# remove empty lines
grep -v '^$' |
# tagging
$TAGGER $OPTIONS $PARFILE | 
perl -pe 's/\tV[BDHV]/\tVB/;s/\tIN\/that/\tIN/;'
