FROM ubuntu:latest
RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
        make \
        texlive \
        texlive-lang-cyrillic \
        texlive-latex-extra \
        texlive-science
RUN apt-get install -y make
ENV uid UID-REPLACE
RUN useradd -m -u $uid -s /bin/bash paper && \
    passwd -l paper
USER paper
VOLUME /tmp/paper
WORKDIR /tmp/paper
CMD ["bash", "-lc", "make"]
